[package]
name = "todo-cli"
version = "0.1.0"
authors = ["Cole"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
urlencoding = "1.1.1"
serde_json = "1.0.59"
base64 = "0.13.0"
